name: Publish
on:
    release:
        types: [published]

jobs:
    #########################################################
    # Publish semver containers
    #########################################################
    build:
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v2
        -   uses: crazy-max/ghaction-docker-meta@v1
            id: docker_meta
            with:
                images: ghcr.io/hipexbv/container-base-nginx
        -   uses: docker/setup-buildx-action@v1.0.4
        -   uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.ACCESS_TOKEN }}
        -   uses: actions/cache@v2
            with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildx-proxy-${{ github.sha }}
                restore-keys: |
                    ${{ runner.os }}-buildx-proxy-
        -   uses: docker/build-push-action@v2.2.2
            with:
                context: .
                push: true
                tags: ${{ steps.docker_meta.outputs.tags }}
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

